# Generated by Django 5.0.6 on 2024-06-06 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('desc', models.TextField()),
                ('que', models.TextField()),
                ('price', models.FloatField()),
                ('category', models.CharField(choices=[('PN', 'Paan Corner'), ('DBE', 'Dairy, Braeds & Eggs'), ('FV', 'Fruits & Vegitables'), ('CDJ', 'Cold Drink & juices'), ('SM', 'Snacks & Munchis'), ('BFIF', 'Breakfast & Instant Food'), ('ST', 'Sweet Tooth'), ('BB', 'Bakery & Biscuits'), ('TCHD', 'Tea,Coffe & Health Drink'), ('ARD', 'Atta,Rice & Da'), ('MOM', 'Masala,Oil & More'), ('SS', 'Sauces & Spreads'), ('CMF', 'Chiken,Meat & Fish'), ('OHL', 'Organic & Healthy Living'), ('BC', 'Baby Care'), ('pw', 'Pharma & Wellness'), ('CE', 'Cleaning Essentials'), ('HO', 'Home & Office'), ('PC', 'Personal Care'), ('PTC', 'Pet Care')], max_length=5)),
                ('subcategory', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='prodcut')),
            ],
        ),
    ]
