# Generated by Django 5.0.6 on 2024-06-19 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0005_category_img"),
    ]

    operations = [
        migrations.CreateModel(
            name="SpecialHeadng",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("description", models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name="category",
            name="img",
            field=models.ImageField(upload_to="category"),
        ),
        migrations.CreateModel(
            name="SpeacialHeadingProduct",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.product"
                    ),
                ),
                (
                    "special_heading",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.specialheadng",
                    ),
                ),
            ],
        ),
    ]
