# Generated by Django 5.0.6 on 2024-06-19 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0006_specialheadng_alter_category_img_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="app.category",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="desc",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="img",
            field=models.ImageField(null=True, upload_to="prodcut"),
        ),
        migrations.AlterField(
            model_name="product",
            name="que",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="subcategory",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="app.subcategory",
            ),
        ),
    ]
