# Generated by Django 5.0.6 on 2024-06-19 17:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0007_alter_product_category_alter_product_desc_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="desc",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="img",
            field=models.ImageField(blank=True, null=True, upload_to="prodcut"),
        ),
        migrations.AlterField(
            model_name="product",
            name="que",
            field=models.TextField(blank=True, null=True),
        ),
    ]
