# Generated by Django 4.1 on 2024-06-16 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_category_alter_product_id_alter_product_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Heading',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('heading_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='heading',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
