# Generated by Django 4.1 on 2024-06-16 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_heading_category_heading'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='heading',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.heading'),
        ),
    ]
