# Generated by Django 5.0.6 on 2024-06-28 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_brand_specialheadng_remove_product_img_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='offer_percent',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
