# Generated by Django 5.0.6 on 2024-07-02 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_cart_is_paid_subcategory_img_alter_cart_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategory',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='product'),
        ),
    ]
