# Generated by Django 5.0.6 on 2024-07-03 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_subcategory_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='units',
        ),
    ]
