# Generated by Django 5.0.6 on 2024-07-03 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_remove_product_units'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='product',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
