# Generated by Django 5.0.6 on 2024-07-09 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_mobilenumber'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_number', models.CharField(max_length=12)),
            ],
        ),
        migrations.DeleteModel(
            name='MobileNumber',
        ),
    ]
