# Generated by Django 5.0.6 on 2024-07-09 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_customer_delete_mobilenumber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='mobile_number',
        ),
        migrations.AddField(
            model_name='customer',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
