# Generated by Django 5.0.6 on 2024-07-15 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_rename_mobile_number_cart_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='customer',
            new_name='mobile_number',
        ),
    ]
