# Generated by Django 5.0.6 on 2024-07-16 01:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='date',
            field=models.TimeField(default=datetime.datetime.today),
        ),
    ]
