# Generated by Django 5.0.6 on 2024-07-18 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_remove_customer_address_remove_customer_city_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomerLocation',
        ),
    ]
