# Generated by Django 5.0.6 on 2024-07-18 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_customer_latitude_customer_longitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='longitude',
        ),
    ]
