# Generated by Django 5.0.6 on 2024-07-18 06:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_order_paid_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='longitude',
        ),
        migrations.CreateModel(
            name='UserAddressBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField()),
                ('status', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.customer')),
            ],
        ),
    ]
