# Generated by Django 5.0.6 on 2024-07-20 10:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0034_remove_customer_latitude_remove_customer_longitude_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PincodeAvailable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pincode", models.CharField(max_length=6)),
            ],
        ),
    ]
