# Generated by Django 5.0.6 on 2024-07-22 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_order_discounted_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='price',
        ),
        migrations.AlterField(
            model_name='order',
            name='discounted_price',
            field=models.IntegerField(null=True),
        ),
    ]
