# Generated by Django 5.0.6 on 2024-07-22 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0040_order_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='discounted_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
