# Generated by Django 5.0.6 on 2024-07-22 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0041_alter_order_discounted_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='discounted_price',
        ),
    ]
