# Generated by Django 5.0.6 on 2024-07-29 11:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0046_customer_verification_code_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="razorpay_order_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
