# Generated by Django 5.0.6 on 2024-07-29 12:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0048_remove_order_discounted_price_remove_order_price_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="razorpay_order_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="razorpay_payment_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="razorpay_signature",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
