# Generated by Django 5.0.6 on 2024-07-29 12:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0049_order_razorpay_order_id_order_razorpay_payment_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="total_price",
            field=models.IntegerField(null=True),
        ),
    ]
