# Generated by Django 5.0.6 on 2024-07-29 13:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0050_order_total_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderproduct",
            name="total_price",
            field=models.IntegerField(null=True),
        ),
    ]
