# Generated by Django 5.0.6 on 2024-08-01 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0050_remove_order_discounted_price_remove_order_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('discounted_price', models.IntegerField(null=True)),
                ('total_price', models.IntegerField(null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.product')),
            ],
        ),
    ]
