# Generated by Django 5.0.6 on 2024-08-28 08:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0051_orderproduct"),
    ]

    operations = [
        migrations.CreateModel(
            name="PhoneOtp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone_number", models.IntegerField()),
                ("otp", models.IntegerField()),
            ],
        ),
    ]
