# Generated by Django 5.0.6 on 2024-08-28 08:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0052_phoneotp"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="phoneotp",
            name="phone_number",
        ),
        migrations.AlterField(
            model_name="phoneotp",
            name="id",
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
