# Generated by Django 5.0.6 on 2024-08-28 08:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0053_remove_phoneotp_phone_number_alter_phoneotp_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="IdOtp",
            fields=[
                (
                    "id",
                    models.CharField(max_length=15, primary_key=True, serialize=False),
                ),
                ("otp", models.IntegerField()),
            ],
        )
        
    ]
