# Generated by Django 5.0.6 on 2024-08-28 09:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0055_idotp_delete_phoneotp"),
    ]

    operations = [
        migrations.AddField(
            model_name="idotp",
            name="phone",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
